<?xml version="1.0" encoding="utf-8"?><Database Name="combugasCC" Class="ContextCombugasDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=softlag.sytes.net;Initial Catalog=combugasCC;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="combugasCCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Bitacora" Member="Bitacora">
    <Type Name="Bitacora">
      <Column Name="id_bitacora" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fechahora" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="id_usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="funcion" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="detalle" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="entidad" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="modulo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.calles" Member="calles">
    <Type Name="calles">
      <Column Name="id_calle" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_zona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_ciudad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_colonia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="id_tipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ciudades_calles" Member="ciudades" ThisKey="id_ciudad" OtherKey="id_ciudad" Type="ciudades" IsForeignKey="true" />
      <Association Name="colonias_calles" Member="colonias" ThisKey="id_colonia" OtherKey="id_colonia" Type="colonias" IsForeignKey="true" />
      <Association Name="estados_calles" Member="estados" ThisKey="id_estado" OtherKey="id_estado" Type="estados" IsForeignKey="true" />
      <Association Name="tipo_calle_calles" Member="tipo_calle" ThisKey="id_tipo" OtherKey="id_tipo" Type="tipo_calle" IsForeignKey="true" />
      <Association Name="zonas_calles" Member="zonas" ThisKey="id_zona" OtherKey="id_zona" Type="zonas" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ciudades" Member="ciudades">
    <Type Name="ciudades">
      <Column Name="id_ciudad" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_zona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ciudades_calles" Member="calles" ThisKey="id_ciudad" OtherKey="id_ciudad" Type="calles" />
      <Association Name="ciudades_colonias" Member="colonias" ThisKey="id_ciudad" OtherKey="id_ciudad" Type="colonias" />
      <Association Name="estados_ciudades" Member="estados" ThisKey="id_estado" OtherKey="id_estado" Type="estados" IsForeignKey="true" />
      <Association Name="zonas_ciudades" Member="zonas" ThisKey="id_zona" OtherKey="id_zona" Type="zonas" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.colonias" Member="colonias">
    <Type Name="colonias">
      <Column Name="id_colonia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_zona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_ciudad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="id_cp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_tipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="colonias_calles" Member="calles" ThisKey="id_colonia" OtherKey="id_colonia" Type="calles" />
      <Association Name="ciudades_colonias" Member="ciudades" ThisKey="id_ciudad" OtherKey="id_ciudad" Type="ciudades" IsForeignKey="true" />
      <Association Name="cp_colonias" Member="cp" ThisKey="id_cp" OtherKey="id_cp" Type="cp" IsForeignKey="true" />
      <Association Name="estados_colonias" Member="estados" ThisKey="id_estado" OtherKey="id_estado" Type="estados" IsForeignKey="true" />
      <Association Name="tipo_asentamiento_colonias" Member="tipo_asentamiento" ThisKey="id_tipo" OtherKey="id_tipo" Type="tipo_asentamiento" IsForeignKey="true" />
      <Association Name="zonas_colonias" Member="zonas" ThisKey="id_zona" OtherKey="id_zona" Type="zonas" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.cp" Member="cp">
    <Type Name="cp">
      <Column Name="id_cp" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_zona" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_estado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="cp_colonias" Member="colonias" ThisKey="id_cp" OtherKey="id_cp" Type="colonias" />
      <Association Name="estados_cp" Member="estados" ThisKey="id_estado" OtherKey="id_estado" Type="estados" IsForeignKey="true" />
      <Association Name="zonas_cp" Member="zonas" ThisKey="id_zona" OtherKey="id_zona" Type="zonas" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.estados" Member="estados">
    <Type Name="estados">
      <Column Name="id_estado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_zona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="estados_calles" Member="calles" ThisKey="id_estado" OtherKey="id_estado" Type="calles" />
      <Association Name="estados_ciudades" Member="ciudades" ThisKey="id_estado" OtherKey="id_estado" Type="ciudades" />
      <Association Name="estados_colonias" Member="colonias" ThisKey="id_estado" OtherKey="id_estado" Type="colonias" />
      <Association Name="estados_cp" Member="cp" ThisKey="id_estado" OtherKey="id_estado" Type="cp" />
      <Association Name="zonas_estados" Member="zonas" ThisKey="id_zona" OtherKey="id_zona" Type="zonas" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.modulos" Member="modulos">
    <Type Name="modulos">
      <Column Name="id_modulo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="titulo" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="url_modulo" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="isactive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="id_modulo_padre" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="orden" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="modulos_permisos" Member="permisos" ThisKey="id_modulo" OtherKey="id_modulo" Type="permisos" />
    </Type>
  </Table>
  <Table Name="dbo.permisos" Member="permisos">
    <Type Name="permisos">
      <Column Name="id_rol_modulo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_rol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_modulo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="observacion" Type="System.String" DbType="VarChar(700) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="modulos_permisos" Member="modulos" ThisKey="id_modulo" OtherKey="id_modulo" Type="modulos" IsForeignKey="true" />
      <Association Name="roles_permisos" Member="roles" ThisKey="id_rol" OtherKey="id_rol" Type="roles" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.roles" Member="roles">
    <Type Name="roles">
      <Column Name="id_rol" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="roles_permisos" Member="permisos" ThisKey="id_rol" OtherKey="id_rol" Type="permisos" />
      <Association Name="roles_usuarios" Member="usuarios" ThisKey="id_rol" OtherKey="id_rol" Type="usuarios" />
    </Type>
  </Table>
  <Table Name="dbo.tipo_asentamiento" Member="tipo_asentamiento">
    <Type Name="tipo_asentamiento">
      <Column Name="id_tipo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="tipo_asentamiento_colonias" Member="colonias" ThisKey="id_tipo" OtherKey="id_tipo" Type="colonias" />
    </Type>
  </Table>
  <Table Name="dbo.tipo_calle" Member="tipo_calle">
    <Type Name="tipo_calle">
      <Column Name="id_tipo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="tipo_calle_calles" Member="calles" ThisKey="id_tipo" OtherKey="id_tipo" Type="calles" />
    </Type>
  </Table>
  <Table Name="dbo.usuarios" Member="usuarios">
    <Type Name="usuarios">
      <Column Name="id_usuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="passwords" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="isactive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="userisonline" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ultimoacceso" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="id_rol" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="horaultimoacceso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="maxsesion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sesionactiva" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="roles_usuarios" Member="roles" ThisKey="id_rol" OtherKey="id_rol" Type="roles" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.zonas" Member="zonas">
    <Type Name="zonas">
      <Column Name="id_zona" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="zonas_calles" Member="calles" ThisKey="id_zona" OtherKey="id_zona" Type="calles" />
      <Association Name="zonas_ciudades" Member="ciudades" ThisKey="id_zona" OtherKey="id_zona" Type="ciudades" />
      <Association Name="zonas_colonias" Member="colonias" ThisKey="id_zona" OtherKey="id_zona" Type="colonias" />
      <Association Name="zonas_cp" Member="cp" ThisKey="id_zona" OtherKey="id_zona" Type="cp" />
      <Association Name="zonas_estados" Member="estados" ThisKey="id_zona" OtherKey="id_zona" Type="estados" />
    </Type>
  </Table>
  <Table Name="dbo.servicio" Member="servicio">
    <Type Name="servicio">
      <Column Name="id_servicio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="alta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="servicio_servicioUnidad" Member="servicioUnidad" ThisKey="id_servicio" OtherKey="id_servicio" Type="servicioUnidad" />
    </Type>
  </Table>
  <Table Name="dbo.servicioUnidad" Member="servicioUnidad">
    <Type Name="servicioUnidad">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_unidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_servicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="alta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="servicio_servicioUnidad" Member="servicio" ThisKey="id_servicio" OtherKey="id_servicio" Type="servicio" IsForeignKey="true" />
      <Association Name="truck_servicioUnidad" Member="truck" ThisKey="id_unidad" OtherKey="id_truck" Type="truck" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.truck" Member="truck">
    <Type Name="truck">
      <Column Name="id_truck" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="numero" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="marca" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="modelo" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="anio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="no_placa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="no_serie" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="alta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="truck_servicioUnidad" Member="servicioUnidad" ThisKey="id_truck" OtherKey="id_unidad" Type="servicioUnidad" />
    </Type>
  </Table>
  <Table Name="dbo.operador" Member="operador">
    <Type Name="operador">
      <Column Name="id_operador" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="alta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>