<?xml version="1.0" encoding="utf-8"?><Database Name="combugasCC" Class="ContextCombugasDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=softlag.sytes.net;Initial Catalog=combugasCC;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="combugasCCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.asigna_ruta_repartidor" Member="asigna_ruta_repartidors">
    <Type Name="asigna_ruta_repartidor">
      <Column Name="id_asigna" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_repartidor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_ruta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="repartidor_asigna_ruta_repartidor" Member="repartidor" ThisKey="id_repartidor" OtherKey="id_repartidor" Type="repartidor" IsForeignKey="true" />
      <Association Name="ruta_asigna_ruta_repartidor" Member="ruta" ThisKey="id_ruta" OtherKey="id_ruta" Type="ruta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.zonas" Member="zonas">
    <Type Name="zona">
      <Column Name="id_zona" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="zona_calle" Member="calles" ThisKey="id_zona" OtherKey="id_zona" Type="calle" />
      <Association Name="zona_ciudade" Member="ciudades" ThisKey="id_zona" OtherKey="id_zona" Type="ciudade" />
      <Association Name="zona_colonia" Member="colonias" ThisKey="id_zona" OtherKey="id_zona" Type="colonia" />
      <Association Name="zona_direccione" Member="direcciones" ThisKey="id_zona" OtherKey="id_zona" Type="direccione" />
      <Association Name="zona_estado" Member="estados" ThisKey="id_zona" OtherKey="id_zona" Type="estado" />
      <Association Name="zona_repartidor" Member="repartidors" ThisKey="id_zona" OtherKey="id_zona" Type="repartidor" />
      <Association Name="zona_ruta" Member="rutas" ThisKey="id_zona" OtherKey="id_zona" Type="ruta" />
    </Type>
  </Table>
  <Table Name="dbo.asigna_ruta_user" Member="asigna_ruta_users">
    <Type Name="asigna_ruta_user">
      <Column Name="id_asigna" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_ruta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="ruta_asigna_ruta_user" Member="ruta" ThisKey="id_ruta" OtherKey="id_ruta" Type="ruta" IsForeignKey="true" />
      <Association Name="usuario_asigna_ruta_user" Member="usuario" ThisKey="id_usuario" OtherKey="id_usuario" Type="usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.calles" Member="calles">
    <Type Name="calle">
      <Column Name="id_calle" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_zona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_ciudad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_colonia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="calle_direccione" Member="direcciones" ThisKey="id_calle" OtherKey="id_calle" Type="direccione" />
      <Association Name="calle_repartidor" Member="repartidors" ThisKey="id_calle" OtherKey="id_calle" Type="repartidor" />
      <Association Name="zona_calle" Member="zona" ThisKey="id_zona" OtherKey="id_zona" Type="zona" IsForeignKey="true" />
      <Association Name="ciudade_calle" Member="ciudade" ThisKey="id_ciudad" OtherKey="id_ciudad" Type="ciudade" IsForeignKey="true" />
      <Association Name="colonia_calle" Member="colonia" ThisKey="id_colonia" OtherKey="id_colonia" Type="colonia" IsForeignKey="true" />
      <Association Name="estado_calle" Member="estado" ThisKey="id_estado" OtherKey="id_estado" Type="estado" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ciudades" Member="ciudades">
    <Type Name="ciudade">
      <Column Name="id_ciudad" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_zona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ciudade_calle" Member="calles" ThisKey="id_ciudad" OtherKey="id_ciudad" Type="calle" />
      <Association Name="ciudade_colonia" Member="colonias" ThisKey="id_ciudad" OtherKey="id_ciudad" Type="colonia" />
      <Association Name="ciudade_direccione" Member="direcciones" ThisKey="id_ciudad" OtherKey="id_ciudad" Type="direccione" />
      <Association Name="ciudade_repartidor" Member="repartidors" ThisKey="id_ciudad" OtherKey="id_ciudad" Type="repartidor" />
      <Association Name="zona_ciudade" Member="zona" ThisKey="id_zona" OtherKey="id_zona" Type="zona" IsForeignKey="true" />
      <Association Name="estado_ciudade" Member="estado" ThisKey="id_estado" OtherKey="id_estado" Type="estado" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.clientes" Member="clientes">
    <Type Name="cliente">
      <Column Name="id_cliente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="celular" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="origen" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="passwords" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="token" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="userisonline" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ultimo_acceso" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="id_tipo_cliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="cliente_direccione" Member="direcciones" ThisKey="id_cliente" OtherKey="id_cliente" Type="direccione" />
      <Association Name="cliente_pedido" Member="pedidos" ThisKey="id_cliente" OtherKey="id_cliente" Type="pedido" />
      <Association Name="tipo_cliente_cliente" Member="tipo_cliente" ThisKey="id_tipo_cliente" OtherKey="id_tipo" Type="tipo_cliente" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.colonias" Member="colonias">
    <Type Name="colonia">
      <Column Name="id_colonia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_zona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_ciudad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="colonia_calle" Member="calles" ThisKey="id_colonia" OtherKey="id_colonia" Type="calle" />
      <Association Name="colonia_direccione" Member="direcciones" ThisKey="id_colonia" OtherKey="id_colonia" Type="direccione" />
      <Association Name="colonia_repartidor" Member="repartidors" ThisKey="id_colonia" OtherKey="id_colonia" Type="repartidor" />
      <Association Name="ciudade_colonia" Member="ciudade" ThisKey="id_ciudad" OtherKey="id_ciudad" Type="ciudade" IsForeignKey="true" />
      <Association Name="zona_colonia" Member="zona" ThisKey="id_zona" OtherKey="id_zona" Type="zona" IsForeignKey="true" />
      <Association Name="estado_colonia" Member="estado" ThisKey="id_estado" OtherKey="id_estado" Type="estado" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.direcciones" Member="direcciones">
    <Type Name="direccione">
      <Column Name="id_direccion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_cliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_zona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_ciudad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_colonia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_calle" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="num_int" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="num_ext" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="entre1" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="entre2" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="referencia" Type="System.String" DbType="VarChar(600)" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="direccione_pedido" Member="pedidos" ThisKey="id_direccion" OtherKey="id_direccion" Type="pedido" />
      <Association Name="calle_direccione" Member="calle" ThisKey="id_calle" OtherKey="id_calle" Type="calle" IsForeignKey="true" />
      <Association Name="ciudade_direccione" Member="ciudade" ThisKey="id_ciudad" OtherKey="id_ciudad" Type="ciudade" IsForeignKey="true" />
      <Association Name="cliente_direccione" Member="cliente" ThisKey="id_cliente" OtherKey="id_cliente" Type="cliente" IsForeignKey="true" />
      <Association Name="colonia_direccione" Member="colonia" ThisKey="id_colonia" OtherKey="id_colonia" Type="colonia" IsForeignKey="true" />
      <Association Name="zona_direccione" Member="zona" ThisKey="id_zona" OtherKey="id_zona" Type="zona" IsForeignKey="true" />
      <Association Name="estado_direccione" Member="estado" ThisKey="id_estado" OtherKey="id_estado" Type="estado" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.estados" Member="estados">
    <Type Name="estado">
      <Column Name="id_estado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_zona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="estado_calle" Member="calles" ThisKey="id_estado" OtherKey="id_estado" Type="calle" />
      <Association Name="estado_ciudade" Member="ciudades" ThisKey="id_estado" OtherKey="id_estado" Type="ciudade" />
      <Association Name="estado_colonia" Member="colonias" ThisKey="id_estado" OtherKey="id_estado" Type="colonia" />
      <Association Name="estado_direccione" Member="direcciones" ThisKey="id_estado" OtherKey="id_estado" Type="direccione" />
      <Association Name="estado_repartidor" Member="repartidors" ThisKey="id_estado" OtherKey="id_estado" Type="repartidor" />
      <Association Name="estado_ruta" Member="rutas" ThisKey="id_estado" OtherKey="id_estado" Type="ruta" />
      <Association Name="zona_estado" Member="zona" ThisKey="id_zona" OtherKey="id_zona" Type="zona" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.formas_pago" Member="formas_pagos">
    <Type Name="formas_pago">
      <Column Name="id_formas_pago" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="formas_pago_pedido" Member="pedidos" ThisKey="id_formas_pago" OtherKey="id_formas_pagos" Type="pedido" />
    </Type>
  </Table>
  <Table Name="dbo.modulos" Member="modulos">
    <Type Name="modulo">
      <Column Name="id_modulo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="titulo" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="url_modulo" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="isactive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="id_modulo_padre" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="modulo_permiso" Member="permisos" ThisKey="id_modulo" OtherKey="id_modulo" Type="permiso" />
    </Type>
  </Table>
  <Table Name="dbo.pedidos" Member="pedidos">
    <Type Name="pedido">
      <Column Name="id_pedido" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_direccion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_cliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_formas_pagos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha_pedido" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="hora_pedido" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="id_usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="radios" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="confirmado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="istomorrow" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="cancelado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="razonCancel" Type="System.String" DbType="VarChar(700)" CanBeNull="true" />
      <Association Name="pedido_pedidos_detalle" Member="pedidos_detalles" ThisKey="id_pedido" OtherKey="id_pedido" Type="pedidos_detalle" />
      <Association Name="cliente_pedido" Member="cliente" ThisKey="id_cliente" OtherKey="id_cliente" Type="cliente" IsForeignKey="true" />
      <Association Name="direccione_pedido" Member="direccione" ThisKey="id_direccion" OtherKey="id_direccion" Type="direccione" IsForeignKey="true" />
      <Association Name="formas_pago_pedido" Member="formas_pago" ThisKey="id_formas_pagos" OtherKey="id_formas_pago" Type="formas_pago" IsForeignKey="true" />
      <Association Name="usuario_pedido" Member="usuario" ThisKey="id_usuario" OtherKey="id_usuario" Type="usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.pedidos_detalle" Member="pedidos_detalles">
    <Type Name="pedidos_detalle">
      <Column Name="id_pedido_detalle" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_pedido" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_servicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cilindros" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_unidad_venta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="total" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="id_precio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fecha_pedido" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="hora_pedido" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="id_usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="pedido_pedidos_detalle" Member="pedido" ThisKey="id_pedido" OtherKey="id_pedido" Type="pedido" IsForeignKey="true" />
      <Association Name="precio_pedidos_detalle" Member="precio" ThisKey="id_precio" OtherKey="id_precio" Type="precio" IsForeignKey="true" />
      <Association Name="servicio_pedidos_detalle" Member="servicio" ThisKey="id_servicio" OtherKey="id_servicio" Type="servicio" IsForeignKey="true" />
      <Association Name="unidad_venta_pedidos_detalle" Member="unidad_venta" ThisKey="id_unidad_venta" OtherKey="id_unidad_venta" Type="unidad_venta" IsForeignKey="true" />
      <Association Name="usuario_pedidos_detalle" Member="usuario" ThisKey="id_usuario" OtherKey="id_usuario" Type="usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.permisos" Member="permisos">
    <Type Name="permiso">
      <Column Name="id_rol_modulo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_rol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_modulo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="observacion" Type="System.String" DbType="VarChar(700) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="modulo_permiso" Member="modulo" ThisKey="id_modulo" OtherKey="id_modulo" Type="modulo" IsForeignKey="true" />
      <Association Name="role_permiso" Member="role" ThisKey="id_rol" OtherKey="id_rol" Type="role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.precios" Member="precios">
    <Type Name="precio">
      <Column Name="id_precio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="precio" Member="precio1" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="id_servicio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_unidad_venta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="precio_pedidos_detalle" Member="pedidos_detalles" ThisKey="id_precio" OtherKey="id_precio" Type="pedidos_detalle" />
      <Association Name="servicio_precio" Member="servicio" ThisKey="id_servicio" OtherKey="id_servicio" Type="servicio" IsForeignKey="true" />
      <Association Name="unidad_venta_precio" Member="unidad_venta" ThisKey="id_unidad_venta" OtherKey="id_unidad_venta" Type="unidad_venta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.repartidor" Member="repartidors">
    <Type Name="repartidor">
      <Column Name="id_repartidor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_tipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="celular" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="id_unidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_zona" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_estado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_ciudad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_colonia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_calle" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="num_int" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="num_ext" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="entre1" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="entre2" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="referencia" Type="System.String" DbType="VarChar(600)" CanBeNull="true" />
      <Association Name="repartidor_asigna_ruta_repartidor" Member="asigna_ruta_repartidors" ThisKey="id_repartidor" OtherKey="id_repartidor" Type="asigna_ruta_repartidor" />
      <Association Name="repartidor_reporte_falla" Member="reporte_fallas" ThisKey="id_repartidor" OtherKey="id_repartidor" Type="reporte_falla" />
      <Association Name="calle_repartidor" Member="calle" ThisKey="id_calle" OtherKey="id_calle" Type="calle" IsForeignKey="true" />
      <Association Name="ciudade_repartidor" Member="ciudade" ThisKey="id_ciudad" OtherKey="id_ciudad" Type="ciudade" IsForeignKey="true" />
      <Association Name="colonia_repartidor" Member="colonia" ThisKey="id_colonia" OtherKey="id_colonia" Type="colonia" IsForeignKey="true" />
      <Association Name="estado_repartidor" Member="estado" ThisKey="id_estado" OtherKey="id_estado" Type="estado" IsForeignKey="true" />
      <Association Name="zona_repartidor" Member="zona" ThisKey="id_zona" OtherKey="id_zona" Type="zona" IsForeignKey="true" />
      <Association Name="tipo_repartidor_repartidor" Member="tipo_repartidor" ThisKey="id_tipo" OtherKey="id_tipo" Type="tipo_repartidor" IsForeignKey="true" />
      <Association Name="unidade_repartidor" Member="unidade" ThisKey="id_unidad" OtherKey="id_unidad" Type="unidade" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.reporte_fallas" Member="reporte_fallas">
    <Type Name="reporte_falla">
      <Column Name="id_reporte" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_repartidor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_ruta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_unidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="observaciones" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(700)" CanBeNull="true" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="hora" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="atendido" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="repartidor_reporte_falla" Member="repartidor" ThisKey="id_repartidor" OtherKey="id_repartidor" Type="repartidor" IsForeignKey="true" />
      <Association Name="ruta_reporte_falla" Member="ruta" ThisKey="id_ruta" OtherKey="id_ruta" Type="ruta" IsForeignKey="true" />
      <Association Name="unidade_reporte_falla" Member="unidade" ThisKey="id_unidad" OtherKey="id_unidad" Type="unidade" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.roles" Member="roles">
    <Type Name="role">
      <Column Name="id_rol" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="role_permiso" Member="permisos" ThisKey="id_rol" OtherKey="id_rol" Type="permiso" />
      <Association Name="role_usuario" Member="usuarios" ThisKey="id_rol" OtherKey="id_rol" Type="usuario" />
    </Type>
  </Table>
  <Table Name="dbo.rutas" Member="rutas">
    <Type Name="ruta">
      <Column Name="id_ruta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="id_zona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ruta_asigna_ruta_repartidor" Member="asigna_ruta_repartidors" ThisKey="id_ruta" OtherKey="id_ruta" Type="asigna_ruta_repartidor" />
      <Association Name="ruta_asigna_ruta_user" Member="asigna_ruta_users" ThisKey="id_ruta" OtherKey="id_ruta" Type="asigna_ruta_user" />
      <Association Name="ruta_reporte_falla" Member="reporte_fallas" ThisKey="id_ruta" OtherKey="id_ruta" Type="reporte_falla" />
      <Association Name="estado_ruta" Member="estado" ThisKey="id_estado" OtherKey="id_estado" Type="estado" IsForeignKey="true" />
      <Association Name="zona_ruta" Member="zona" ThisKey="id_zona" OtherKey="id_zona" Type="zona" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.servicios" Member="servicios">
    <Type Name="servicio">
      <Column Name="id_servicio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="servicio_pedidos_detalle" Member="pedidos_detalles" ThisKey="id_servicio" OtherKey="id_servicio" Type="pedidos_detalle" />
      <Association Name="servicio_precio" Member="precios" ThisKey="id_servicio" OtherKey="id_servicio" Type="precio" />
    </Type>
  </Table>
  <Table Name="dbo.tipo_clientes" Member="tipo_clientes">
    <Type Name="tipo_cliente">
      <Column Name="id_tipo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="tipo_cliente_cliente" Member="clientes" ThisKey="id_tipo" OtherKey="id_tipo_cliente" Type="cliente" />
    </Type>
  </Table>
  <Table Name="dbo.tipo_repartidor" Member="tipo_repartidors">
    <Type Name="tipo_repartidor">
      <Column Name="id_tipo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tipo_repartidor_repartidor" Member="repartidors" ThisKey="id_tipo" OtherKey="id_tipo" Type="repartidor" />
    </Type>
  </Table>
  <Table Name="dbo.unidad_venta" Member="unidad_ventas">
    <Type Name="unidad_venta">
      <Column Name="id_unidad_venta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="unidad_venta_pedidos_detalle" Member="pedidos_detalles" ThisKey="id_unidad_venta" OtherKey="id_unidad_venta" Type="pedidos_detalle" />
      <Association Name="unidad_venta_precio" Member="precios" ThisKey="id_unidad_venta" OtherKey="id_unidad_venta" Type="precio" />
    </Type>
  </Table>
  <Table Name="dbo.unidades" Member="unidades">
    <Type Name="unidade">
      <Column Name="id_unidad" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="mantenimiento" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="unidade_repartidor" Member="repartidors" ThisKey="id_unidad" OtherKey="id_unidad" Type="repartidor" />
      <Association Name="unidade_reporte_falla" Member="reporte_fallas" ThisKey="id_unidad" OtherKey="id_unidad" Type="reporte_falla" />
    </Type>
  </Table>
  <Table Name="dbo.usuarios" Member="usuarios">
    <Type Name="usuario">
      <Column Name="id_usuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="passwords" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="isactive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="userisonline" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ultimoacceso" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="id_rol" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="horaultimoacceso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="usuario_asigna_ruta_user" Member="asigna_ruta_users" ThisKey="id_usuario" OtherKey="id_usuario" Type="asigna_ruta_user" />
      <Association Name="usuario_pedido" Member="pedidos" ThisKey="id_usuario" OtherKey="id_usuario" Type="pedido" />
      <Association Name="usuario_pedidos_detalle" Member="pedidos_detalles" ThisKey="id_usuario" OtherKey="id_usuario" Type="pedidos_detalle" />
      <Association Name="role_usuario" Member="role" ThisKey="id_rol" OtherKey="id_rol" Type="role" IsForeignKey="true" />
    </Type>
  </Table>
</Database>